<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blitter\Blitter.csproj" />
    <ProjectReference Include="..\Blitter.Bits\Blitter.Bits.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Blitter.Blocks3D.Tests" />
  </ItemGroup>

</Project>
